### ISSUE TITLE
🐛[Bug] Types imported with `~/` prefixes cannot be resolved locally

### ISSUE THREAD

**Issue by scott-seguno** [Shopify/discount-app-components#51]
## Issue summary

Often in this codebase, import statements are written like `import type {RecurringPaymentType} from '~/constants';` (for example, [here](https://github.com/Shopify/discount-app-components/blob/main/src/components/UsageLimitsCard/UsageLimitsCard.tsx#L15)). The `~/` prefix results in Typescript errors.

## Expected behavior

Types should be referenced using relative paths that don't include a tilde.

## Actual behavior

This results in Typescript errors like the following:
```
node_modules/@shopify/discount-app-components/build/ts/latest/src/components/CountriesAndRatesCard/utilities.d.ts:2:30 - error TS2307: Cannot find module '~/types' or its corresponding type declarations.

2 import type { Country } from '~/types';
                               ~~~~~~~~~
```

## Workaround

There are two workarounds. First, you can disable type checking for the `discount-app-components` dependency, which is not optimal since we would not be able to verify types. The alternative is to declare an ambient module that re-exports the types:
```
declare module '~/types' {
	export * from '@shopify/discount-app-components/build/ts/latest/src/types';
}
```

**Comment by devisscher** [comment]
@scott-seguno do you have a bit more info or reproduction steps on this issue. We tried to reproduce this issue in a consuming project but haven't seen the issue. 

If you have any more info that could help us narrow down the issue.

Thanks in advance!

**Comment by scott-seguno** [comment]
> discount-app-components

@devisscher Sure thing! Attached is a sample project; just run `npm it` and it should install and test. I left comments to explain various issues, but the workaround is to uncomment the lines in `types.d.ts`. Let me know if I can provide anything further, and thanks for looking into it!

[discount-app-components-test.zip](https://github.com/Shopify/discount-app-components/files/12443324/discount-app-components-test.zip)

**Comment by scott-seguno** [comment]
@devisscher sorry; I should clarify... the issue with the `Country` import from my original description can be easily resolved with `import { type Country } from "@shopify/discount-app-components";`, which works perfectly fine; I used that to showcase the issues with using tilde expansions inside import statements within the `discount-app-component` source code. For example, I import `UsageLimitsCard` in `test-file.tsx`, but typescript cannot locate the `Field` type in the [UsageLimitsCard](https://github.com/Shopify/discount-app-components/blob/1a6b76cf1f996dad9acdbcbca21e00a1574b86c5/src/components/UsageLimitsCard/UsageLimitsCard.tsx#L15) due to the import statement there: `import type {Field, PositiveNumericString} from '~/types';`.
