### ISSUE TITLE
❓[Question] React 18 support?

### ISSUE THREAD

**Issue by pnmcosta** [Shopify/discount-app-components#70]
Polaris is now `^18.0.0` see [this](https://github.com/Shopify/polaris/blob/main/polaris-react/package.json#L68). 

This package is preventing me from updating my app, is this planned to be updated too?

Thank you

**Comment by bithaolee** [comment]
We had the same problem

**Comment by pnmcosta** [comment]
Hey @bithaolee, how did you get it solved? Did you manually upgrade refs on this project?

I'm working on it here: https://github.com/pnmcosta/discount-app-components-v11 but I have very limitted FE experience and am haven't progressed with the jest update.

Happy to take contributions and move it forward quicker.

**Comment by pnmcosta** [comment]
FYI `npm i @shopify/discount-app-components@pnmcosta/discount-app-components-v11` seems to be working fine for me, but I had to change the build-verify scripts to accommodate my build runners.
